server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;

        # Sin esto, al refrescar /orders Nginx devuelve 404.
        # Con esto, siempre sirve index.html y React Router maneja la ruta.
        try_files $uri $uri/ /index.html;
    }
}
